### PR TITLE
Website integration changes

### PR DESCRIPTION
**Pull request by jmmabanta**
Main changes are try/excepting all imports so that the website can properly import the repo while not disrupting the workflow for those who don't use the website. This can be done  with less lines of code using relative imports but I've heard these may be unreliable at times.

Another change is adding 'dummy' as an interface option so the software can generate its own dummy responses.

### CODE REVIEW

**Review by Taylorr82 — DISMISSED** [review]

**Comment by jmmabanta** [comment]
Have these import changes impacted any of the OBC software team's development environments? If not, can these changes be merged to master so website's integration can be kept up to date more easily?

**Comment by Taylorr82** [comment]
Looks like we forgot about this pr. Since it's quite old, could you rebase it with master?

**Comment by jmmabanta** [comment]
Done rebasing! If it's not needed, I can remove the Github actions task of auto-regenerating CommandDocs.txt (only when system.py is modified) as the website's command parser automatically does that outside this repo.

**Comment by Taylorr82** [comment]
Another conflict appeared! sorry!

**Review by Taylorr82 — DISMISSED** [review]
Seems to work just fine. Not a fan of the relative includes but if they're necessary I guess that's ok

**Comment by jmmabanta** [comment]
Fixed the merge conflict (it was just the dummy interface interfering with the SDR interface)

**Review by Taylorr82 — DISMISSED** [review]

**Comment by jmmabanta** [comment]
Only other change is making documentation generation only run on PRs to master (in addition to only when system.py changes). This has been tested in my own fork which works as expected. Merging to master now

**Pull request merged**
