### PR TITLE
Use npm to install yarn

### PR DESCRIPTION
**Pull request by Taylorr82**
This is how yarnpkg.com recommends to install yarn

### CODE REVIEW

**Review by jmmabanta — APPROVED** [review]
If npm is being used to install yarn, you can use `npm run <script name>` instead of needing yarn (though at the cost of losing "muscle memory"). I'm indifferent towards it so its your call (for its main use cases here, both npm and yarn are functionally identical at running scripts in package.json)

**Comment by jmmabanta** [comment]
Try:
```bash
npm run sat_cli -- -I sdr
```
Apparently npm requires `--` to [separate cli arguments](https://docs.npmjs.com/cli/v8/commands/npm-run-script).

**Comment by Taylorr82** [comment]
> Try:
> 
> ```shell
> npm run sat_cli -- -I sdr
> ```
> 
> Apparently npm requires `--` to [separate cli arguments](https://docs.npmjs.com/cli/v8/commands/npm-run-script).

Maybe we should stick with yarn for familiarity. Most of our staff aren't familiar with cli's

**Comment by jmmabanta** [comment]
Good call, its mostly just preference between the two anyways

**Pull request merged**
