### PR TITLE
removed pipe notifaction cmd

### PR DESCRIPTION
**Pull request by jlazzz**
thought this change got captured in one of Robert's recent PRs, but guess not.

### CODE REVIEW

**Comment by Taylorr82** [comment]
What's the reason for this?

**Comment by joshdellaz** [comment]
No, but if the changes in this PR aren't implemented, then nothing works over uhf at all.

**Comment by Taylorr82** [comment]
How does it not work at all? This notification was there before I refactored the uhtranceiver class

**Comment by joshdellaz** [comment]
I could be wrong actually, it was a while ago. Regardless, this is dead functionality that we're not using any more, I'm not sure why I need to justify it any further.

**Comment by Taylorr82** [comment]
Because it's a big design change that I wasn't aware of. Also, system.py still has this subservice in it.

**Comment by Taylorr82** [comment]
Remove the subservice from system.py and update the OBC software to start the pipe mode timer based on the string received from UHF

**Review by Taylorr82 — APPROVED** [review]

**Pull request merged**
